version: '3.8'

services:
  frontend:
    build: ./example-frontend
    container_name: frontend
  backend:
    build: ./example-backend
    environment:
      - REDIS_HOST=cache
      - POSTGRES_HOST=postgres
    container_name: backend
  cache:
    image: redis:7.0
    restart: unless-stopped
    command: redis-server
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
    container_name: reverse-proxy
