version: '3.8'

services:
  frontend:
    build: ./example-frontend
    ports:
      - '5000:5000'
  backend:
    build: ./example-backend
    ports:
      - '8080:8080'
    environment:
      - REDIS_HOST=cache
      - POSTGRES_HOST=postgres
  cache:
    image: redis:7.0
    restart: unless-stopped
    command: redis-server
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
